import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
// import styles from '@/styles/Home.module.css';
import styles from '@/styles/StyleGlobal.module.css';
import { Header } from '@/shared/components/organism/Header';
import { Products } from '@/shared/components/templates/Products';
import { ProviderProducts } from '@/context/Provider';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ProviderProducts>
          <Header />
          <Products />
        </ProviderProducts>
      </main>
    </>
  );
}
